config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:create, :index, :show, :new] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :grade, numericality: { only_integer: true,
    greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    if params[:query].present?
      @cocktails = Cocktail.where('name LIKE ?', "%#{params[:query]}%")
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    @dose = Dose.new
    @reviews = @cocktail.reviews
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new # needed to instantiate the form_for
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @doses = @cocktail.doses
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @reviews = @cocktail.reviews
      @review = Review.new
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    @reviews = @cocktail.reviews
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @doses = @cocktail.doses
      @dose = Dose.new
      render 'cocktail/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @cocktail = @review.cocktail
    @review.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content, :grade)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="justify-center">
  <div class="cards p-3">
    <% @cocktails.each do |cocktail| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 150, width: 150, crop: :fill %>')">
        <h3 class="card-title card-title-link"><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="new-form-container container m-3">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wisk.ai/wp-content/uploads/2019/07/liquor-inventory-scale-2.jpg);">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <p>Hell of a cocktail!</p>
  </div>
</div>

<!-- Intro Card with name and recipe -->

<div class="cards-container overlap text-align-center">

  <!-- Title card -->
  <div class="container">
    <div class="card  align-middle mb-3 w-100" style="width: 18rem;">
      <!-- Contains the info about restaurant -->
      <div class="card-body">
        <h3 class="card-title"><%= @cocktail.name %></h5>
        <p class="card-text">Recipe</p>
      </div>
    </div>
  </div>

  <!-- Info & Form container -->

  <div class="container d-flex">

    <div class="card align-middle w-100" style="width: 18rem;">
      <!-- Contains the info about restaurant -->
      <div class="card-body">
        <h3 class="card-title">Info</h3>
        <p class="card-text">Description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi temporibus facilis id nemo aperiam sunt optio doloremque ducimus minus pariatur, tempore numquam dolorum autem culpa ea voluptatum aspernatur, molestiae repellat.</p>
        <% dose_index = 0 %>
        <h3 class="card-title">Doses</h3>
        <% @doses.each do |dose| %>
          <% dose_index += 1 %>
          <div class="flex">
            <p class="">Dose <%= dose_index %> - <%= dose.description %> of <%= dose.ingredient.name %>.
            <%= link_to dose_path(dose), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </div>
        <% end %></p>
      </div>
    </div>

    <!-- Form to add a dose -->
    <div class="card align-middle w-90">
      <img src="https://image.freepik.com/free-photo/male-bartender-pouring-cocktail-from-shaker_23-2148209359.jpg" class="card-img-top" alt="...">
      <div class="card-body">
      <button class="btn btn-primary w-100" id="add-ing-button">Add a dose!</button>

        <div id="form-dose-none">
          <h3 class="card-title">New dose</h3>
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :description%>
            <%= f.association :ingredient %>
            <%= f.submit class: 'btn btn-success w-100'%>
          <% end %>
        </div>
      </div>
    </div>
  </div>



  <div class="container my-3">
    <div class="card align-middle w-100 p-3">
        <div class="card-body">
          <h3 class="card-title">Cocktail reviews</h3>
          <% review_index = 0 %>
          <% @reviews.each do |review| %>
            <% review_index += 1 %>
            <p>Review <%= review_index %> - <%= review.content %>. <span class="badge badge-primary badge-pill">
              <% counter = 0 %>
              <% 5.times do %>
                <i class="fa <%= review.grade > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                <% counter += 1 %>
              <% end %>
            </span> <%= link_to review_path(review), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %></p>
          <% end %>
        </div>
        <button class="btn btn-primary w-100" id="add-rev-button">Add a review!</button>
        <div class="card align-middle w-100" id="form-review-none">
          <div class="card-body">
            <h3 class="card-title">Add a review</h3>
            <%= simple_form_for [@cocktail, @review] do |f| %>
              <%= f.input :content%>
              <%= f.input :grade %>
              <%= f.submit class: 'btn btn-success w-100'%>
            <% end %>
          </div>
        </div>
    </div>
  </div>

  <div class="container mt-3">
  <%= link_to 'Back', cocktails_path, :class => "btn btn-danger w-100 align-bottom" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar.html.erb" %>
    <%= yield %>
    <script src="../../javascript/packs/application.js"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top mb-6 navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group no-margin">
      <input class="form-control string required" type="text" name="query" id="search_query" value="<%= params[:query] %>" placeholder="Case Sensitive" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>


  <%= link_to new_cocktail_path, class: "navbar-brand" do %>
    <%= image_tag "add.png" %>
  <% end %>
</div>